# Generated by Django 4.1.2 on 2022-11-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=models.FileField(default=None, null=True, upload_to='notice/'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.FileField(default=None, null=True, upload_to='notice/'),
        ),
    ]
