# Generated by Django 4.1.2 on 2022-11-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skul', '0002_alter_homework_content_alter_notice_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='content',
        ),
    ]
